#!/bin/bash

ISROOT="$(whoami | grep '^root$')"

if [ -n "$ISROOT" ]; then
	lxc-ls -1 | while read container; do
		lxc-info -n $container | grep 'State:[ \t]\+STOPPED' > /dev/null
		if [ $? -eq 0 ]; then
			echo -n "Starting $container..."
			lxc-start -n $container
			echo "done"
		fi
	done
else
	echo "Requires root access"
fi
